### ISSUE TITLE
2eindes??

### ISSUE THREAD

**Issue by njittam** [RSDT/Japp16#119]
![screenshot_20171016-131359](https://user-images.githubusercontent.com/6692452/31609339-05620d94-b274-11e7-8908-4fc8f5c34bbe.png)

**Comment by njittam** [comment]
mickys site doet dit ook.

**Comment by Area348** [comment]
Ik denk dat dit test data is met hergebruikte coords is. Dus dat het 2 lijntjes heen en weer zijn....
