### ISSUE TITLE
inzittenden autos bijhouden

### ISSUE THREAD

**Issue by njittam** [RSDT/Japp16#53]
Voor volgend jaar:
op de website bijhouden wie er bij wie in de auto zitten.
dan hoef je ook geen huntnaam meer in te stellen in de app.

**Comment by Area348** [comment]
Hoeft ook niet persee nu. Maar is gewoon handig als je de naam aanpast.
Bij houden doen we in google-sheets.

(Zie nog niet direct namelijk hoe/ wat er van te maken)

**Comment by njittam** [comment]
verplaatst naar RSDT/JH-API#3
