### ISSUE TITLE
Lege infowindow scoutingroepen

### ISSUE THREAD

**Issue by njittam** [RSDT/Japp16#71]
sommige scoutingingroepen hebben een leeg infowindow.
bijv geldermalsen en gorssel

**Comment by Dingenis** [comment]
Dit komt waarschijnlijk doordat de text te lang is bij die scouting groepen, ik dacht dat ik dit al gefixt had door de textview Singeline te zetten en een Ellipsize te zetten.

**Comment by Area348** [comment]
Hier is dat geen probleem ik heb gewoon de info in het window staan, 
Moet ik er wel bij zeggen dat ik in mijn mob de tekst op klein heb staan.

**Comment by njittam** [comment]
Kun je niet een /n toevoegen na sparie als ie te lang is?
