### ISSUE TITLE
Verbeteringen & ideeën voor volgend jaar

### ISSUE THREAD

**Issue by Dingenis** [RSDT/Japp16#75]
JAPP
- [x] Volgen met noord boven.
- [x] Eigen tail kleur in app. Bij deelgebied blauw, Niet blauw
- [ ] !!!! Wissel tussen de 2 dagen !!! dat je de vossen van dag 1 uit kunt zetten!!!!!
- [x] Kleuren in deelgebied uit kunnen zetten (rand mag blijven).
- [ ] Lengte staart in stellen.
- [ ] Betere uitleg over hoe je de app kan gebruiken(spot/hunt/marken/etc)
- [ ] Huntnaam obsolete maken door het toevoegen van een auto systeem

SITE-Micky:

- [ ] Openstreetmaps
- [x] Vossen invoer pagina, met voor iedere vos een regel RD-RD, +1x tijd. !! lege invoer moet geen probleem zijn. (liefst via textarea voor copy past).
- [ ] Coord check via bovenstaande textarea.
- [x] Coord check ook de optie om de dagdelen te splitsen.
- [x] Laatste Loc, Spot, Hunt, andere kleur dan rest van de stippen (opacity??)
- [ ] En geen getalletjes in laten vullen door gebruiker van spots en hunts

Site-Mattijn:
- [ ] ABSOLUUT de website ook auto updateable (JS) maken op de kaart ;), scheeld volgens mij enorm in de lag met het inladen.
- [ ] Er zit een bug in de site die hunts/spots niet als laatste groei cirkel gebruikt.
- [ ] Zie bovenstaande van SITE-Micky alles mbt de map.

Bot
- [ ] geen spam bij restart
- [ ] aangeven wanneer er weer gehunt mag worden.

Algemeen/API
- [x] aankunnen geven of er al een tegenhunt is geweest op een blokhut. (alleen voor onze eigen HB).
- [x] autos bijhouden

**Comment by Area348** [comment]
Eigen tail kleur in app. Bij deelgebied blauw, Niet blauw

**Comment by njittam** [comment]
bot:
geen spam bij restart
aangeven wanneer er weer gehunt mag worden.

**Comment by njittam** [comment]
algemeen autos bijhouden.

app aankunnen geven of er al een tegenhunt is geweest op een blokhut.

**Comment by njittam** [comment]
voor puntje openstreetmaps en js kaart.
kijk ff naar openlayers

**Comment by njittam** [comment]
ik heb voor alle puntjes een losse issue aangemaakt.
