### ISSUE TITLE
Locatie wordt niet elke minuut verzonden?

### ISSUE THREAD

**Issue by njittam** [RSDT/Japp16#97]
Als ik soms op m'n eigen Hunt locatie klik is doe 10 minuten oud.

**Comment by Dingenis** [comment]
Waarschijnlijk te maken met het auto update systeem wat niet meer werkt, waardoor je nieuwe locatie niet word opgehaald

**Comment by njittam** [comment]
ik denk dat dit gwn aan de gps in de telefoon ligt
